server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: postgres
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.vmms.*.daomain
